# Generated by Django 4.1 on 2023-08-01 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categories",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom_categorie",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="nom de la categorie",
                    ),
                ),
                (
                    "created_at_categorie",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date creation de la categorie"
                    ),
                ),
                (
                    "date_de_publication_categorie",
                    models.DateField(
                        default="2022-11-10",
                        verbose_name="date de publication de la categorie ",
                    ),
                ),
                (
                    "image_categorie",
                    models.ImageField(
                        upload_to="categories/",
                        verbose_name="image de la categorie du modele",
                    ),
                ),
            ],
            options={"verbose_name": "categorie",},
        ),
        migrations.CreateModel(
            name="Modeles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom_modele",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="nom modele"
                    ),
                ),
                (
                    "created_at_modele",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date creation du modele"
                    ),
                ),
                (
                    "date_de_publication",
                    models.DateField(
                        default="2022-11-10",
                        verbose_name="date de publication du modele ",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="categories/", verbose_name="image du modele"
                    ),
                ),
                (
                    "categorie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalogue.categories",
                    ),
                ),
            ],
            options={"verbose_name": "modele",},
        ),
        migrations.CreateModel(
            name="Image_details",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "img_detail",
                    models.ImageField(
                        upload_to="categories/",
                        verbose_name="image de profile du modele",
                    ),
                ),
                (
                    "created_at_detail_modele",
                    models.DateTimeField(
                        auto_now_add=True,
                        verbose_name="date creation de la detail du modele",
                    ),
                ),
                (
                    "date_de_publication_detail_modele",
                    models.DateField(
                        default="2022-11-10",
                        verbose_name="date de publication du de la detail du modele ",
                    ),
                ),
                (
                    "img_detail_modele",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalogue.modeles",
                    ),
                ),
            ],
            options={"verbose_name": "image detail du modele",},
        ),
    ]
